version: 2.1

orbs:
  node: circleci/node@4.7.0
jobs:
  build_and_deploy_staging:
    docker:
      - image: "cimg/node:16.17"
    steps:
      - checkout
      - run:
          name: download & unzip awscli v2
          command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip
      - run:
          name: install awscli v2
          command: sudo ./aws/install
      - restore_cache:
          key: safe-react-apps-deps-{{ checksum "package.json" }}
      - run:
          name: install yarn dependencies
          command: yarn
      - save_cache:
          key: safe-react-apps-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: production build
          command: yarn build
      - run:
          name: s3 sync
          command: aws s3 sync ./apps/tx-builder/build/ s3://staging-meter-io/ --delete
      - run:
          name: invalidation
          command: aws cloudfront create-invalidation --distribution-id E1UOEAVTH2TKKE --paths "/*"

workflows:
  fresh_deploy:
    jobs:
      - build_and_deploy_staging:
          context:
            - aws-2023
            - slack-secrets
          filters:
            branches:
              only:
                - development
